#PLEASE REMEMBER TO DELETE ALL <> AND CHANGE THE NAMES/STRING OF CHARACTERS IN SAID <>
networks:
  # If the application is needed to talk to database apps uncomment this network
  # <db_network_name>:
  #   driver: bridge
  #   external: true
  # If the application needs to go through traefik use this network
  <proxy_network_name>:
    external: true
    driver: bridge
  # I like having a default docker network
  <srv_net>:
    driver: bridge
    external: true

services:
  # Portainer a container management system
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
  # Make sure you change this to whatever you named your docker socket proxy container_name
    command: -H tcp://<docker_sp>:2375
    volumes:
      - /<container_location>/portainer/appdata:/data
    networks:
      - <proxy_network_name>
  # I recommend keeping the ports exposed just incase traefik goes down
    ports:
      - 9000:9000
    environment:
      TZ: <time_zone>
      PUID: <users_UID>
      PGID: <users_GID>
  # Make sure you change this to whatever you named your docker socket proxy container_name
      DOCKER_HOST: "tcp://<docker_sp>:2375"
    # labels:
      # traefik.enable: true
  # Uncomment out the below line if you want to change the service url from <container name>.<domain.com> to something else
      # traefik.http.routers.<container_name>.rule: Host(`<name>.<domain.com>`)
  # Use auth-secure@file if you want the application to use authelia for multi-factor authentication
      # traefik.http.routers.<container_name>.middlewares: noauth-secure@file
      # traefik.http.routers.portainer.entrypoints: websecure
      # traefik.http.routers.portainer.service: svc-portainer
      # traefik.http.services.svc-portainer.loadBalancer.server.port: 9000
